name: assop2b-__ENV__

services:
  website:
    container_name: assop2b-__ENV__-website
    build:
      context: ./assop2b-website
    expose:
      - "3000"
    networks:
      - assop2b-__ENV__

  fe-admin:
    container_name: assop2b-__ENV__-fe-admin
    build:
      context: ./assop2b-fe-admin
      args:
        VITE_API_BASE_URL: https://${DOMAIN_API}
    expose:
      - "80"
    networks:
      - assop2b-__ENV__

  be-admin:
    container_name: assop2b-__ENV__-be-admin
    build:
      context: ./assop2b-be-admin
    expose:
      - "8080"
    networks:
      - assop2b-__ENV__

networks:
  assop2b-__ENV__:
    name: assop2b-__ENV__
